version: '3.1'

services:
  s_api_1:
    container_name: c_api_1
    image: kmlcn1/api1
    build:
      context: .
      dockerfile: secondProject/Dockerfile
    ports:
      - 9000:80
   

  s_api_2:
    container_name: c_api_2
    image: kmlcn1/api2
    ports:
      - 5000:80